"""Migrations creation

Revision ID: 5ae944339750
Revises: 
Create Date: 2024-02-29 18:03:02.383878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ae944339750'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pages', 'title',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
    op.alter_column('pages', 'last_time_visited',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pages', 'last_time_visited',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('pages', 'title',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
    # ### end Alembic commands ###
