"""changed columns

Revision ID: c611b84a3c4b
Revises: f89a257577b0
Create Date: 2024-04-29 12:22:17.026084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c611b84a3c4b'
down_revision: Union[str, None] = 'f89a257577b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pages', sa.Column('tags', sa.ARRAY(sa.VARCHAR()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pages', 'tags')
    # ### end Alembic commands ###
